### PR TITLE
Simple federated cluster environment

### PR DESCRIPTION
**Pull request by jspaleta**
Introduces a federated cluster environment.
### Notable changes
* Needed to refector the seed scripting to allow for different seeding arrangements for gateway versus downstream clusters in the federated environment.
* added several federation specific configuration directories
* added dedicated init script for federation to make use of refectored seed script using optional env_vars to point to federation config directories

I've tested refactor against docker-compose-default to ensure script refactor don't impact existing operation.

### CODE REVIEW

**Comment by calebhailey** [comment]
Some initial thoughts from a first pass review: 

* Can we consolidate some of the duplicate config files into a `/config/sensu/defaults/` subdirectory instead of managing redundant files? 
* Do we need multiple postgres DB servers (distinct containers), or can we treat the postgres DB server as a shared service like we were already doing ([for Sensu + sample app + Mattermost](https://github.com/sensu/sensu-go-workshop/tree/latest/config/postgres/scripts))?

**Comment by jspaleta** [comment]
>     * Can we consolidate some of the duplicate config files into a `/config/sensu/defaults/` subdirectory instead of managing redundant files?
yes..but I wasn't sure what was going to be redundant until after i got it working..and this will require refactoring the non federated init script. Didn't want to over optimize on first pass and break everything.

> 
>     * Do we need multiple postgres DB servers (distinct containers), or can we treat the postgres DB server as a shared service like we were already doing ([for Sensu + sample app + Mattermost](https://github.com/sensu/sensu-go-workshop/tree/latest/config/postgres/scripts))?

yes..
But this would either require a significant refactoring of how the single postgres db is configured to allow for context specific config scripts. Or it would require the common postgres db to provisioned with all expected databases for all compose scenarions.

Also... there are failure modes that we can test by making sure we have different postgres servers running.. mimicking what a real geographically separated federated cluster env looks like. By running separate postgres servers as if they were in separate data centers of regions... we can use the federated env to explore "sensu monitor thyself" scenarios.

**Comment by jspaleta** [comment]
> Some initial thoughts from a first pass review:
> 
>     * Can we consolidate some of the duplicate config files into a `/config/sensu/defaults/` subdirectory instead of managing redundant files?
> 
>     * Do we need multiple postgres DB servers (distinct containers), or can we treat the postgres DB server as a shared service like we were already doing ([for Sensu + sample app + Mattermost](https://github.com/sensu/sensu-go-workshop/tree/latest/config/postgres/scripts))?

@calebhailey I've refactored the configuration to remove file duplication and reduced postgres containers back down to a single container.

**Review by calebhailey — COMMENTED** [review]
LGTM 👍

**Pull request merged**
